In [33]:
import tensorflow as tf

# Tensor 연산
<br>

1.산술연산<br>
2.논리연산<br>
3.기타연산<br>

<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/math">참고링크</a>
<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/linalg/matmul">행렬연산 참고링크</a>
<br>

### case1.산술연산
* point(element-wise) operation
    * add
    * subtract
    * multiply
    * divide


In [49]:
a, b = tf.constant([2.2]), tf.constant([-1.0])
c, d = tf.constant([1.1,2.2]), tf.constant([-1.0])

In [35]:
#add(덧셈)
c1 = tf.add(a,b)
c1

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [36]:
#subtract(빼기)
c2 = tf.subtract(a,b)
c2

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.2], dtype=float32)>

In [37]:
#multiply(곱셈))
c3 = tf.multiply(a,b)
c4 = tf.multiply(c,d)
print(c3)
print(c4)

tf.Tensor([-2.2], shape=(1,), dtype=float32)
tf.Tensor([-1.1 -2.2], shape=(2,), dtype=float32)


In [38]:
#divide(나눗셈)
c5 = tf.divide(a,b)
c6 = tf.divide(c,d)
print(c5)
print(c6)

tf.Tensor([-2.2], shape=(1,), dtype=float32)
tf.Tensor([-1.1 -2.2], shape=(2,), dtype=float32)


<br>

* matrix operation
    * point(element)-wise product
    * dot product

In [39]:
a, b = tf.constant([1.1, 2.2]), tf.constant([-1.0, -2.0])
c, d = tf.constant([[1.1, 2.2]]), tf.constant([[-1.0],[-2.0]])

In [40]:
#point-wise product
c7 = tf.multiply(a,b)
c7
print(c,d)

tf.Tensor([[1.1 2.2]], shape=(1, 2), dtype=float32) tf.Tensor(
[[-1.]
 [-2.]], shape=(2, 1), dtype=float32)


In [41]:
#dot product
c8 = tf.matmul(c,d)
c9 = tf.matmul(c,tf.transpose(c))
print(c8)
print(c9)

tf.Tensor([[-5.5]], shape=(1, 1), dtype=float32)
tf.Tensor([[6.05]], shape=(1, 1), dtype=float32)


<br><br>

### Case2.논리연산자

* and
* or
* xor
* not

In [42]:
x = tf.constant([False, False, True, True])
y = tf.constant([False, True, False, True])

In [43]:
d1 = tf.logical_and(x,y) #비교 대상이 모두 true 인경우: true
d2 = tf.logical_or(x,y) #비교 대상들 중 하나라도 true인경우: true
d3 = tf.math.logical_xor(x,y) #비교 대상들이 모두 false, 모두 true가 아닌경우: true/ tf.logical_xor(x,y) --> math 추가 안해주면 error 메시지 발생
d4 = tf.logical_not(x) #true값을 false로, false값을 true로 변경

print("d1결과 입니다: "+str(d1))
print("d2결과 입니다: "+str(d2))
print("d3결과 입니다: "+str(d3))
print("d4결과 입니다: "+str(d4))

d1결과 입니다: tf.Tensor([False False False  True], shape=(4,), dtype=bool)
d2결과 입니다: tf.Tensor([False  True  True  True], shape=(4,), dtype=bool)
d3결과 입니다: tf.Tensor([False  True  True False], shape=(4,), dtype=bool)
d4결과 입니다: tf.Tensor([ True  True False False], shape=(4,), dtype=bool)


<br><br>

### Case4.기타연산
* pow
* exp
* log
* square
* sqrt

In [53]:
a = tf.constant([[2,2,2],[3,3,3]])

In [45]:
#pow (제곱연산) -> y=a^3 -> element(point) wise
b = tf.pow(a,3)
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8,  8,  8],
       [27, 27, 27]])>

In [46]:
#exp (지수값) --> y=e^x
#정수형태의 값들을 exp 적용시 error 발생
c = tf.cast(a, tf.float32)
d = tf.exp(c)
d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 7.389056,  7.389056,  7.389056],
       [20.085537, 20.085537, 20.085537]], dtype=float32)>

In [47]:
#log (로그값) --> y=logex -> 자연로그 값; e는 밑수
#정수형태의 값들을 exp 적용시 error 발생
e = tf.cast(a, tf.float32)
f = tf.math.log(e)
f

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6931472, 0.6931472, 0.6931472],
       [1.0986123, 1.0986123, 1.0986123]], dtype=float32)>

In [54]:
#square -> y=x^2 -> 제곱값
g = tf.square(a)
g

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [9, 9, 9]])>

In [55]:
#sqrt -> 제곱근값
#정수형태의 값들을 exp 적용시 error 발생
h = tf.cast(a, tf.float32)
i = tf.sqrt(h)
i

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.4142135, 1.4142135, 1.4142135],
       [1.7320508, 1.7320508, 1.7320508]], dtype=float32)>