In [2]:
import tensorflow as tf

# Tensor란?

1. Tensor는 선형대수와 물리학에서 사용되던 개념 <br>
2. Tensorflow는 tensor가 다차원 배열로 나타낼 수 있다는 개념을 차용함 <br>
3. 그래서, Tensorflow는 tensor를 동적크기를 갖는 다차원 배열이라고 정의 <br>
4. Tensorflow는 tensor를 기본 자료구조로써 사용하며, tensor를 통해 모든 데이터를 표현 <br>

<br>

<center>
<img src="figure/1.jpg"><br>
<a href="https://statkclee.github.io/deep-learning/tensorflow-data-structure.html" width="600" height="400" style="color:white">figure1. 수학적 개념에서의 tensor</a>
</center>

<br><br><br><br>

Tensorflow에서 사용되는 rank라는 개념은 행렬에서 사용하는 rank와 다른 개념이다. Tensorflow에서의 rank는 단지 차원을 의미하며 아래와 같은 개념들과 동의어로 사용되고 있다.<br>
rank:order,degree,dimension

<center>
<img src="figure/2.png"><br>
<a href="https://www.tensorflow.org/guide/tensor" style="color:white">figure2. tensorflow에서의 rank</a>
</center>

<br><br><br><br>
Case1. 0차원 배열

In [3]:
tensor_a = tf.constant(100)

In [4]:
#Tensor 정보 출력
tensor_a

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [5]:
#tensor는 0차원 배열을 갖음
tensor_a.shape

TensorShape([])

<center>
<img src="figure/3.png"><br>
<a href="https://www.tensorflow.org/guide/tensor" style="color:white">figure3. tensorflow에서의 shape</a>
</center>

In [6]:
#tensor가 갖고있는 값의 자료형
tensor_a.dtype

tf.int32

In [8]:
#tensor가 갖고있는 값
tensor_a.numpy()

100

<br><br><br><br>
Case2. 1차원배열

In [9]:
tensor_b = tf.constant([100])

In [7]:
# shape(1,) -> 1차원 배열을 의미
tensor_b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([100])>

In [8]:
tensor_b.dtype

tf.int32

<br><br><br><br>
Case3. 2차원배열

In [11]:
tensor_c = tf.constant([[100,200],[300,400]])

In [12]:
tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]])>

In [13]:
#2차원 배열에서 (0,0) 값 출력 -> 수학적으로는 1행1열
tensor_c[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=100>

<br><br><br><br>
Case4. 3차원배열

In [14]:
tensor_d = tf.constant([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

<center>
<img src="figure/4.jpg"><br>
figure4. 3차원 배열의 기하적 구조
</center>

In [15]:
#2x3x4 3차원 배열
tensor_d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [16]:
tensor_d[0][0][3]

<tf.Tensor: shape=(), dtype=int32, numpy=4>