In [1]:
import tensorflow as tf

# Tensor 변환
1. 생성된 tensor 값을 변환시키는 방법에 대해서 알아본다.<br>
2. 생성된 tensor를 조작하는 방법에 대해서 알아본다.<br>

<br><br>

## 1.Tensor값 변환시키는 방법

* tf.zeros_like
* tf.ones_like



In [10]:
a = tf.random.normal([2,2], mean=3, stddev=0.1)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.9200583, 3.1004748],
       [2.8635175, 3.032741 ]], dtype=float32)>

<br><br>

### Case1. tf.zeros_like
* a 텐서의 모든 값을 0으로 변경

In [11]:
b = tf.zeros_like(a)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

<br><br>

### Case2. tf.ones_like
* a 텐서의 모든 값을 1로 변경

In [12]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

<br><br>

## 2.Tensor를 조작시키는 방법

* Tensor자료형 변환
* Tensor shape 변환
* Tensor 차원 변환
* Tensor 자르고 붙이기

<br>


In [29]:
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<br>
### Case1. Tensor 자료형 변환<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/cast">자료형 변환 참고 API</a>

In [30]:
b = tf.dtypes.cast(a, tf.float64)
b

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

<br>
### Case2. Tensor shape 변환 <br>
<a href="https://www.tensorflow.org/api_docs/python/tf/reshape">Shape 변환 참고 API</a>

In [39]:
a = tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [42]:
# [2D -> 1D 행렬로 변환]
b = tf.reshape(a, [6]) #reshape(텐서, 텐서 shape)
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [43]:
# [1D -> 2D 행렬로 변환]
c = tf.reshape(b,[2,3]) 
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>