In [1]:
import tensorflow as tf

# Tensor 생성방법 <br>
Tensor를 생성하는 대부분 방법은 numpy 패키지에서 차용한 개념이기 때문에, numpy를 생성하는 함수와 유사한걸 볼 수 있다.


<br><br>

## Tensor를 생성하는 기본적인 방법에 대해서 배워보자.

* 상수값을 갖는 tensor 생성
    * tf.constant
    * tf.zeros
    * tf.ones
    * tf.fill

<br>

### Case1. tf.constant

In [31]:
# 지정된 값을 갖는 텐서를 생성
a = tf.constant([2.3,3])
a

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.3, 3. ], dtype=float32)>

<br>

### Case2. tf.zeros

In [18]:
# 모든 값을 0으로 초기화한 텐서를 생성
b = tf.zeros([2,3])
b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
# 모든 값을 1로 초기화한 텐서를 생성
c = tf.zeros([2])
c


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

<br>

### Case3. tf.fill

In [28]:
# 모든 값을 'value'값으로 초기화한 텐서를 생성
d = tf.fill([2,3],4) #tf.fill(dims=[2,3],value=4)
d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4]])>

<br><br><br>
* 난수값을 갖는 tensor 생성
    * tf.random_normal
    * tf.random_unifrom

<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/random/">radom 속성 API 링크</a>

<br>

### Case1. tf.random.normal

In [38]:
# 정규분포를 따르는 난수 생성
# 평균근처의 값들이 난수로 생성될 확률이 높다
a = tf.random.normal([2], mean=-1, stddev=4)
b = tf.random.normal([2,3], mean=2, stddev=0.1)
a
b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.0722637, 2.158355 , 2.227394 ],
       [2.1465344, 1.9708643, 2.0902605]], dtype=float32)>

<img src="figure/chapter2/1.png" width="400" height="300">
<br>
<a href="https://needjarvis.tistory.com/66">figure1. normal distribution (정규분포표)</a>

<br>

### Case2. tf.random.uniform

In [41]:
# 균등분포가 정규분포와 다른점은 평균근처에서 난수가 생성될 확률이 높은것이 아니라,
# (a,b] = (0,2] 구간의 난수들이 고른 확률로 랜덤하게 생성된다.
c = tf.random.uniform([2,3],0,2) #tf.random.uniform([2,3], minval=0, maxval=2)
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.8617225 , 1.9989071 , 1.3731294 ],
       [1.6962495 , 0.14238787, 1.3759277 ]], dtype=float32)>

<img src="figure/chapter2/2.png" width="400" height="300">
<br>
<a href="https://en.wikipedia.org/wiki/Discrete_uniform_distribution">figure2. uniform distribution (균등분포표)</a>