In [1]:
import tensorflow as tf

In [2]:
tensor_a = tf.constant(100)

In [3]:
#Tensor 정보 출력
tensor_a

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [4]:
#Tensor 모양: 몇차원 배열인지
tensor_a.shape

TensorShape([])

In [5]:
#해당 tensor는 0차원 배열을 갖음\n",
tensor_a.numpy()

100

In [6]:
tensor_b = tf.constant([100])

In [7]:
# shape(1,) -> 1차원 배열을 의미\n",
tensor_b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([100])>

In [8]:
tensor_b.dtype

tf.int32

In [9]:
tensor_c = tf.constant([[100,200],[300,400]])

In [10]:
tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]])>

In [11]:
tensor_d = tf.constant([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [12]:
#2차원 배열에서 (0,0) 값 출력 -> 수학적으로는 1행1열
tensor_c[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [13]:
#2x3x4 3차원 배열
tensor_d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [14]:
tensor_d[0][0][3]

<tf.Tensor: shape=(), dtype=int32, numpy=4>