In [2]:
import tensorflow as tf

# Tensor 변환
1. 생성된 tensor 값을 변환시키는 방법에 대해서 알아본다.<br>
2. 생성된 tensor를 조작하는 방법에 대해서 알아본다.<br>

<br><br>

## 1.Tensor값 변환시키는 방법

* tf.zeros_like
* tf.ones_like



In [10]:
a = tf.random.normal([2,2], mean=3, stddev=0.1)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.9200583, 3.1004748],
       [2.8635175, 3.032741 ]], dtype=float32)>

<br><br>

### Case1. tf.zeros_like
* a 텐서의 모든 값을 0으로 변경

In [11]:
b = tf.zeros_like(a)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

<br><br>

### Case2. tf.ones_like
* a 텐서의 모든 값을 1로 변경

In [12]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

<br><br>

## 2.Tensor를 조작시키는 방법

* Tensor자료형 변환
* Tensor shape(or 차원) 변환
* Tensor 자르고 붙이기

<br>


In [29]:
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<br>
### Case1. Tensor 자료형 변환<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/cast">자료형 변환 참고 API</a>

In [30]:
b = tf.dtypes.cast(a, tf.float64)
b

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

<br>

### Case2. Tensor shape 변환
<br>
<a href="https://www.tensorflow.org/api_docs/python/tf/reshape">Shape 변환 참고 API</a>

In [39]:
a = tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [42]:
# [2D -> 1D 행렬로 변환]
b = tf.reshape(a, [6]) #reshape(텐서, 텐서 shape)
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [43]:
# [1D -> 2D 행렬로 변환]
c = tf.reshape(b,[2,3]) 
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
# 크기 1인 차원을 텐서에 추가
d = tf.constant([[1,2],[3,4]])
print("현재 텐서의 형태는 " + str(d.shape))
print("현재 텐서의 차원은 " + str(d.ndim))
print("=======텐서추가=========")
e = tf.expand_dims(d,1) #만약 (d,2)인 경우에는 --> (2,2,1)이라고 출력
print("추가된 텐서의 형태는 " + str(e.shape))
print("추가된 텐서의 차원은 " + str(e.ndim))

현재 텐서의 형태는 (2, 2)
현재 텐서의 차원은 2
=======텐서추가=========
추가된 텐서의 형태는 (2, 1, 2)
추가된 텐서의 차원은 3


In [23]:
# 크기 1인 차원을 텐서에서 제거
f = tf.constant([[[1],[3],[5]]])
print("현재 텐서의 형태는 " + str(f.shape))
print("현재 텐서의 차원은 " + str(f.ndim))
print("=======1차원 텐서제거=========")
g = tf.squeeze(f) #만약 (d,2)인 경우에는 --> (2,2,1)이라고 출력
print("제거된 텐서의 형태는 " + str(g.shape))
print("제거된 텐서의 차원은 " + str(g.ndim))
print("=======1차원 텐서제거(특정위치)=========")
h = tf.squeeze(f,[0]) #[2]라고 설정할 경우 --> (1,3)=1x3 행렬을 출력
print("제거된 텐서의 형태는 " + str(h.shape))
print("제거된 텐서의 차원은 " + str(h.ndim))

현재 텐서의 형태는 (1, 3, 1)
현재 텐서의 차원은 3
=======1차원 텐서제거=========
제거된 텐서의 형태는 (3,)
제거된 텐서의 차원은 1
=======1차원 텐서제거(특정위치)=========
제거된 텐서의 형태는 (3, 1)
제거된 텐서의 차원은 2


<br>

### Case3. Tensor 자르고 붙이기

In [79]:
a = tf.constant([1,2,3,4,5,6,7,8,9])
b = tf.constant([[1,2,3,4,5,6],[7,8,9,0,1,2]])
c = tf.constant([[[1, 1, 1], [2, 2, 2]],[[3, 3, 3], [4, 4, 4]], [[5, 5, 5], [6, 6, 6]]])
print(a)
print(b)
print(c)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 9 0 1 2]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]], shape=(3, 2, 3), dtype=int32)


In [39]:
#Tensor 자르기
d = tf.slice(a, [2],[3]) # [시작인덱스][끝인덱스]
e = tf.slice(b, [0,2],[1,2]) #[0,2]위치를 기점으로 (1x2) 크기(=size) 만큼의 tensor를 잘라내겠다.
f = tf.slice(c, [1,0,0],[1,1,3]) #[1,0,0]위치를 시작(원점)이라고 했을때, (1x1x3) 크기(=size)만큼의 텐서를 잘라내겠다. 
g = tf.slice(c, [1,0,0],[2,1,3]) #[1,0,0]위치를 시작(원점)이라고 했을때, (2x1x3) 크기(=size)만큼의 텐서를 잘라내겠다.
print(d)
print(e)
print(f)
print(g)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([[3 4]], shape=(1, 2), dtype=int32)
tf.Tensor([[[3 3 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[3 3 3]]

 [[5 5 5]]], shape=(2, 1, 3), dtype=int32)


In [130]:
#Tensor 분할하기
#주의사항 텐서를 나눌 경우, 나누어지는 텐서의 크기가 모두 동일해야한다
#ex) [1,2,3,4,5] 텐서가 있는데, 2로 나누면 [1,2],[3,4],[5] 텐서로 나뉘는데, [5] 크기가 다르므로 에러가 발생한다.
h = tf.split(a,3) # "tf.split(a,3,0)과 동일한 코드" /  a 텐서 모양 = (9) --> (3),(3),(3) --> 열을 기준으로 텐서가 3개로 나뉨 
i = tf.split(b,2,0) #b 텐서 모양 = (2,6) --> (1,6),(1,6) --> 행을 기준으로 텐서가 2개로 나뉨
j = tf.split(b,2,1) #b 텐서 모양 = (2,6) --> (2,3),(2,3) --> 열을 기준으로 텐서가 2개로 나뉨
k = tf.split(c,3,2) #c 텐서 모양 = (3,2,3) --> (3,2,1), (3,2,1), (3,2,1) --> 열을 기준으로 텐서가 3개로 나뉨
l = tf.split(c,2,1) #c 텐서 모양 = (3,2,3) --> (3,1,3), (3,1,3) --> 행을 기준으로 텐서가 2개로 나뉨
# 결론=세번째 index --> 0:열, 1:행, 2:depth/ 이를 일반화시키면 대수적으로 이해가 가능
print("===================h결과====================")
print("split 이전 h 텐서")
print(a)
print("split 이후 h 텐서")
print(h)
print("===================i결과=====================")
print("split 이전 i 텐서")
print(b)
print("split 이후 i 텐서")
print(i)
print("===================j결과=====================")
print("split 이전 j 텐서")
print(b)
print("split 이후 j 텐서")
print(j)
print("===================k결과=====================")
print("split 이전 k 텐서")
print(c)
print("split 이후 k 텐서")
print(k)
print("===================l결과=====================")
print("split 이전 l 텐서")
print(c)
print("split 이후 l 텐서")
print(l)


===================h결과====================
split 이전 h 텐서
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
split 이후 h 텐서
[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9])>]
===================i결과=====================
split 이전 i 텐서
tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 9 0 1 2]], shape=(2, 6), dtype=int32)
split 이후 i 텐서
[<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]])>, <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[7, 8, 9, 0, 1, 2]])>]
===================j결과=====================
split 이전 j 텐서
tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 9 0 1 2]], shape=(2, 6), dtype=int32)
split 이후 j 텐서
[<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]])>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [0, 1, 2]])>]
===================k결과=====================
split 이전 k 텐서
tf.Tensor(
[[[1 1 1]
 

In [150]:
#Tensor 붙이기
#입력할 텐서들의 차원은 모두 동일해야한다.
t1 = [[1, 2, 3], [4, 5, 6]] #shape: 2x3
t2 = [[7, 8, 9], [10, 11, 12]] #shape: 2x3
t3 = tf.concat([t1, t2],0)  #(2x3) 2개 --concat--> (4x3) 
t4 = tf.concat([t1, t2],1) #(2x3) 2개 --concat--> (2x6) 
print("==============t3결과=============")
print(t3)
print("==============t4결과=============")
print(t4)

==============t3결과=============
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
==============t4결과=============
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [154]:
#Tensor 붙이기
#입력할 텐서들의 차원은 모두 동일해야한다.
t5 = [[[1,2],[3,4]],[[5,6],[7,8]]] #shape: 2x2x2
t6 = [[[9,10],[11,12]],[[13,14],[15,16]]] #shape: 2x2x2
t7 = tf.concat([t5,t6],0) #(2x2x2) 2개 --concat--> (4x2x2)
t8 = tf.concat([t5,t6],1) #(2x2x2) 2개 --concat--> (2x4x2)
t9 = tf.concat([t5,t6],2) #(2x2x2) 2개 --concat-->(2x2x4)
print("==============t7결과=============")
print(t7)
print("==============t8결과=============")
print(t8)
print("==============t9결과=============")
print(t9)

==============t7결과=============
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]], shape=(4, 2, 2), dtype=int32)
==============t8결과=============
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]], shape=(2, 4, 2), dtype=int32)
==============t9결과=============
tf.Tensor(
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]], shape=(2, 2, 4), dtype=int32)
